# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tldx < Formula
  desc "tldx is a fast, developer-first CLI tool for researching available domains across multiple TLDs with permutations"
  homepage ""
  version "1.2.5"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/brandonyoungdev/tldx/releases/download/v1.2.5/tldx_1.2.5_darwin_amd64.tar.gz"
      sha256 "b4cab506ec1af6d218daa7d3b2a8635c3906e27b79d4e557f1e5c7968d8e2b50"

      def install
        bin.install "tldx"
      end
    end
    on_arm do
      url "https://github.com/brandonyoungdev/tldx/releases/download/v1.2.5/tldx_1.2.5_darwin_arm64.tar.gz"
      sha256 "6611fdf234daa2a34bc289d28e0597d9f692f7a7a77f1a1cb367a413b4256451"

      def install
        bin.install "tldx"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brandonyoungdev/tldx/releases/download/v1.2.5/tldx_1.2.5_linux_amd64.tar.gz"
        sha256 "3767b879bd885c9b29c4e82a7cb226068feb25e3b389e551f6f730a9eb8fd863"

        def install
          bin.install "tldx"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brandonyoungdev/tldx/releases/download/v1.2.5/tldx_1.2.5_linux_arm64.tar.gz"
        sha256 "0eab4909825efc7ba5ac27d5f57368a95db26cd6fd4dec286534bfc33517d75d"

        def install
          bin.install "tldx"
        end
      end
    end
  end
end
