# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tldx < Formula
  desc "tldx is a fast, developer-first CLI tool for researching available domains across multiple TLDs with permutations"
  homepage ""
  version "1.3.4"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/brandonyoungdev/tldx/releases/download/v1.3.4/tldx_1.3.4_darwin_amd64.tar.gz"
      sha256 "8873f3c5e17eac56a936201c4fc9d7657a08bbefbc7738b56e7f62a94719f0b5"

      def install
        bin.install "tldx"
      end
    end
    on_arm do
      url "https://github.com/brandonyoungdev/tldx/releases/download/v1.3.4/tldx_1.3.4_darwin_arm64.tar.gz"
      sha256 "739b202e171f6e2dfb1cd498e682f6f4f6e3f148dbccb9071d2a46d73c0e9c04"

      def install
        bin.install "tldx"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brandonyoungdev/tldx/releases/download/v1.3.4/tldx_1.3.4_linux_amd64.tar.gz"
        sha256 "66218cbc02d6c2e219c3f40c50df4d29d8082cdfa747f8bc229c4ccbe351e211"

        def install
          bin.install "tldx"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/brandonyoungdev/tldx/releases/download/v1.3.4/tldx_1.3.4_linux_arm64.tar.gz"
        sha256 "bb33e8a919ae21aac88c027c6b13767ab9b749401911fb47966b3be8235fa123"

        def install
          bin.install "tldx"
        end
      end
    end
  end
end
